// Offcanvas

import {
  MODAL_INNER_PADDING,
  MODAL_CONTENT_BORDER_COLOR,
  MODAL_CONTENT_BORDER_WIDTH,
  MODAL_TITLE_LINE_HEIGHT,
  MODAL_CONTENT_BG,
  MODAL_CONTENT_COLOR,
  MODAL_CONTENT_BOX_SHADOW_XS,
  MODAL_BACKDROP_BG,
  MODAL_BACKDROP_OPACITY,
} from './modal';

// scss-docs-start offcanvas-variables
export const OFFCANVAS_PADDING_Y = MODAL_INNER_PADDING;
export const OFFCANVAS_PADDING_X = MODAL_INNER_PADDING;
export const OFFCANVAS_HORIZONTAL_WIDTH: string = '400px';
export const OFFCANVAS_VERTICAL_HEIGHT: string = '30vh';
export const OFFCANVAS_TRANSITION_DURATION: string = '.3s';
export const OFFCANVAS_BORDER_COLOR = MODAL_CONTENT_BORDER_COLOR;
export const OFFCANVAS_BORDER_WIDTH = MODAL_CONTENT_BORDER_WIDTH;
export const OFFCANVAS_TITLE_LINE_HEIGHT = MODAL_TITLE_LINE_HEIGHT;
export const OFFCANVAS_BG_COLOR = MODAL_CONTENT_BG;
export const OFFCANVAS_COLOR = MODAL_CONTENT_COLOR;
export const OFFCANVAS_BOX_SHADOW = MODAL_CONTENT_BOX_SHADOW_XS;
export const OFFCANVAS_BACKDROP_BG = MODAL_BACKDROP_BG;
export const OFFCANVAS_BACKDROP_OPACITY = MODAL_BACKDROP_OPACITY;
// scss-docs-end offcanvas-variables
