const FLEX = {
  flex: {
    fill: 'flex-fill',
  },
  'flex-sm': {
    fill: 'flex-sm-fill',
  },
  'flex-md': {
    fill: 'flex-md-fill',
  },
  'flex-lg': {
    fill: 'flex-lg-fill',
  },
  'flex-xl': {
    fill: 'flex-xl-fill',
  },
  'flex-xxl': {
    fill: 'flex-xxl-fill',
  },
  'flex-direction': {
    row: 'flex-row',
    column: 'flex-column',
    'row-reverse': 'flex-row-reverse',
    'column-reverse': 'flex-column-reverse',
  },
  'flex-direction-sm': {
    row: 'flex-sm-row',
    column: 'flex-sm-column',
    'row-reverse': 'flex-sm-row-reverse',
    'column-reverse': 'flex-sm-column-reverse',
  },
  'flex-direction-md': {
    row: 'flex-md-row',
    column: 'flex-md-column',
    'row-reverse': 'flex-md-row-reverse',
    'column-reverse': 'flex-md-column-reverse',
  },
  'flex-direction-lg': {
    row: 'flex-lg-row',
    column: 'flex-lg-column',
    'row-reverse': 'flex-lg-row-reverse',
    'column-reverse': 'flex-lg-column-reverse',
  },
  'flex-direction-xl': {
    row: 'flex-xl-row',
    column: 'flex-xl-column',
    'row-reverse': 'flex-xl-row-reverse',
    'column-reverse': 'flex-xl-column-reverse',
  },
  'flex-direction-xxl': {
    row: 'flex-xxl-row',
    column: 'flex-xxl-column',
    'row-reverse': 'flex-xxl-row-reverse',
    'column-reverse': 'flex-xxl-column-reverse',
  },
  'flex-grow': {
    0: 'flex-grow-0',
    1: 'flex-grow-1',
  },
  'flex-grow-sm': {
    0: 'flex-sm-grow-0',
    1: 'flex-sm-grow-1',
  },
  'flex-grow-md': {
    0: 'flex-md-grow-0',
    1: 'flex-md-grow-1',
  },
  'flex-grow-lg': {
    0: 'flex-lg-grow-0',
    1: 'flex-lg-grow-1',
  },
  'flex-grow-xl': {
    0: 'flex-xl-grow-0',
    1: 'flex-xl-grow-1',
  },
  'flex-grow-xxl': {
    0: 'flex-xxl-grow-0',
    1: 'flex-xxl-grow-1',
  },
  'flex-shrink': {
    0: 'flex-shrink-0',
    1: 'flex-shrink-1',
  },
  'flex-shrink-sm': {
    0: 'flex-sm-shrink-0',
    1: 'flex-sm-shrink-1',
  },
  'flex-shrink-md': {
    0: 'flex-md-shrink-0',
    1: 'flex-md-shrink-1',
  },
  'flex-shrink-lg': {
    0: 'flex-lg-shrink-0',
    1: 'flex-lg-shrink-1',
  },
  'flex-shrink-xl': {
    0: 'flex-xl-shrink-0',
    1: 'flex-xl-shrink-1',
  },
  'flex-shrink-xxl': {
    0: 'flex-xxl-shrink-0',
    1: 'flex-xxl-shrink-1',
  },
  'flex-wrap': {
    wrap: 'flex-wrap',
    'no-wrap': 'flex-nowrap',
    'wrap-reverse': 'flex-wrap-reverse',
  },
  'flex-wrap-sm': {
    wrap: 'flex-sm-wrap',
    'no-wrap': 'flex-sm-nowrap',
    'wrap-reverse': 'flex-sm-wrap-reverse',
  },
  'flex-wrap-md': {
    wrap: 'flex-md-wrap',
    'no-wrap': 'flex-md-nowrap',
    'wrap-reverse': 'flex-md-wrap-reverse',
  },
  'flex-wrap-lg': {
    wrap: 'flex-lg-wrap',
    'no-wrap': 'flex-lg-nowrap',
    'wrap-reverse': 'flex-lg-wrap-reverse',
  },
  'flex-wrap-xl': {
    wrap: 'flex-xl-wrap',
    'no-wrap': 'flex-xl-nowrap',
    'wrap-reverse': 'flex-xl-wrap-reverse',
  },
  'flex-wrap-xxl': {
    wrap: 'flex-xxl-wrap',
    'no-wrap': 'flex-xxl-nowrap',
    'wrap-reverse': 'flex-xxl-wrap-reverse',
  },
  gap: {
    0: 'gap-0',
    1: 'gap-1',
    2: 'gap-2',
    3: 'gap-3',
    4: 'gap-4',
    5: 'gap-5',
  },
  'gap-sm': {
    0: 'gap-sm-0',
    1: 'gap-sm-1',
    2: 'gap-sm-2',
    3: 'gap-sm-3',
    4: 'gap-sm-4',
    5: 'gap-sm-5',
  },
  'gap-md': {
    0: 'gap-md-0',
    1: 'gap-md-1',
    2: 'gap-md-2',
    3: 'gap-md-3',
    4: 'gap-md-4',
    5: 'gap-md-5',
  },
  'gap-lg': {
    0: 'gap-lg-0',
    1: 'gap-lg-1',
    2: 'gap-lg-2',
    3: 'gap-lg-3',
    4: 'gap-lg-4',
    5: 'gap-lg-5',
  },
  'gap-xl': {
    0: 'gap-xl-0',
    1: 'gap-xl-1',
    2: 'gap-xl-2',
    3: 'gap-xl-3',
    4: 'gap-xl-4',
    5: 'gap-xl-5',
  },
  'gap-xxl': {
    0: 'gap-xxl-0',
    1: 'gap-xxl-1',
    2: 'gap-xxl-2',
    3: 'gap-xxl-3',
    4: 'gap-xxl-4',
    5: 'gap-xxl-5',
  },
  'justify-content': {
    start: 'justify-content-start',
    end: 'justify-content-end',
    center: 'justify-content-center',
    between: 'justify-content-between',
    around: 'justify-content-around',
    evenly: 'justify-content-evenly',
  },
  'justify-content-sm': {
    start: 'justify-content-sm-start',
    end: 'justify-content-sm-end',
    center: 'justify-content-sm-center',
    between: 'justify-content-sm-between',
    around: 'justify-content-sm-around',
    evenly: 'justify-content-sm-evenly',
  },
  'justify-content-md': {
    start: 'justify-content-md-start',
    end: 'justify-content-md-end',
    center: 'justify-content-md-center',
    between: 'justify-content-md-between',
    around: 'justify-content-md-around',
    evenly: 'justify-content-md-evenly',
  },
  'justify-content-lg': {
    star: 'justify-content-lg-start',
    end: 'justify-content-lg-end',
    center: 'justify-content-lg-center',
    between: 'justify-content-lg-between',
    around: 'justify-content-lg-around',
    evenly: 'justify-content-lg-evenly',
  },
  'justify-content-xl': {
    start: 'justify-content-xl-start',
    end: 'justify-content-xl-end',
    center: 'justify-content-xl-center',
    between: 'justify-content-xl-between',
    around: 'justify-content-xl-around',
    evenly: 'justify-content-xl-evenly',
  },
  'justify-content-xxl': {
    start: 'justify-content-xxl-start',
    end: 'justify-content-xxl-end',
    center: 'justify-content-xxl-center',
    between: 'justify-content-xxl-between',
    around: 'justify-content-xxl-around',
    evenly: 'justify-content-xxl-evenly',
  },
  'align-items': {
    start: 'align-items-start',
    end: 'align-items-end',
    center: 'align-items-center',
    baseline: 'align-items-baseline',
    stretch: 'align-items-stretch',
  },
  'align-items-sm': {
    start: 'align-items-sm-start',
    end: 'align-items-sm-end',
    center: 'align-items-sm-center',
    baseline: 'align-items-sm-baseline',
    stretch: 'align-items-sm-stretch',
  },
  'align-items-md': {
    start: 'align-items-md-start',
    end: 'align-items-md-end',
    center: 'align-items-md-center',
    baseline: 'align-items-md-baseline',
    stretch: 'align-items-md-stretch',
  },
  'align-items-lg': {
    start: 'align-items-lg-start',
    end: 'align-items-lg-end',
    center: 'align-items-lg-center',
    baseline: 'align-items-lg-baseline',
    stretch: 'align-items-lg-stretch',
  },
  'align-items-xl': {
    start: 'align-items-xl-start',
    end: 'align-items-xl-end',
    center: 'align-items-xl-center',
    baseline: 'align-items-xl-baseline',
    stretch: 'align-items-xl-stretch',
  },
  'align-items-xxl': {
    start: 'align-items-xxl-start',
    end: 'align-items-xxl-end',
    center: 'align-items-xxl-center',
    baseline: 'align-items-xxl-baseline',
    stretch: 'align-items-xxl-stretch',
  },
  'align-content': {
    start: 'align-content-start',
    end: 'align-content-end',
    center: 'align-content-center',
    between: 'align-content-between',
    around: 'align-content-around',
    stretch: 'align-content-stretch',
  },
  'align-content-sm': {
    start: 'align-content-sm-start',
    end: 'align-content-sm-end',
    center: 'align-content-sm-center',
    between: 'align-content-sm-between',
    around: 'align-content-sm-around',
    stretch: 'align-content-sm-stretch',
  },
  'align-content-md': {
    start: 'align-content-md-start',
    end: 'align-content-md-end',
    center: 'align-content-md-center',
    between: 'align-content-md-between',
    around: 'align-content-md-around',
    stretch: 'align-content-md-stretch',
  },
  'align-content-lg': {
    start: 'align-content-lg-start',
    end: 'align-content-lg-end',
    center: 'align-content-lg-center',
    between: 'align-content-lg-between',
    around: 'align-content-lg-around',
    stretch: 'align-content-lg-stretch',
  },
  'align-content-xl': {
    start: 'align-content-xl-start',
    end: 'align-content-xl-end',
    center: 'align-content-xl-center',
    between: 'align-content-xl-between',
    around: 'align-content-xl-around',
    stretch: 'align-content-xl-stretch',
  },
  'align-content-xxl': {
    start: 'align-content-xxl-start',
    end: 'align-content-xxl-end',
    center: 'align-content-xxl-center',
    between: 'align-content-xxl-between',
    around: 'align-content-xxl-around',
    stretch: 'align-content-xxl-stretch',
  },
  'align-self': {
    auto: 'align-self-auto',
    start: 'align-self-start',
    end: 'align-self-end',
    center: 'align-self-center',
    baseline: 'align-self-baseline',
    stretch: 'align-self-stretch',
  },
  'align-self-sm': {
    auto: 'align-self-sm-auto',
    start: 'align-self-sm-start',
    end: 'align-self-sm-end',
    center: 'align-self-sm-center',
    baseline: 'align-self-sm-baseline',
    stretch: 'align-self-sm-stretch',
  },
  'align-self-md': {
    auto: 'align-self-md-auto',
    start: 'align-self-md-start',
    end: 'align-self-md-end',
    center: 'align-self-md-center',
    baseline: 'align-self-md-baseline',
    stretch: 'align-self-md-stretch',
  },
  'align-self-lg': {
    auto: 'align-self-lg-auto',
    start: 'align-self-lg-start',
    end: 'align-self-lg-end',
    center: 'align-self-lg-center',
    baseline: 'align-self-lg-baseline',
    stretch: 'align-self-lg-stretch',
  },
  'align-self-xl': {
    auto: 'align-self-xl-auto',
    start: 'align-self-xl-start',
    end: 'align-self-xl-end',
    center: 'align-self-xl-center',
    baseline: 'align-self-xl-baseline',
    stretch: 'align-self-xl-stretch',
  },
  'align-self-xxl': {
    auto: 'align-self-xxl-auto',
    start: 'align-self-xxl-start',
    end: 'align-self-xxl-end',
    center: 'align-self-xxl-center',
    baseline: 'align-self-xxl-baseline',
    stretch: 'align-self-xxl-stretch',
  },
  order: {
    first: 'order-first',
    0: 'order-0',
    1: 'order-1',
    2: 'order-2',
    3: 'order-3',
    4: 'order-4',
    5: 'order-5',
    last: 'order-last',
  },
  'order-sm': {
    first: 'order-sm-first',
    0: 'order-sm-0',
    1: 'order-sm-1',
    2: 'order-sm-2',
    3: 'order-sm-3',
    4: 'order-sm-4',
    5: 'order-sm-5',
    last: 'order-sm-last',
  },
  'order-md': {
    first: 'order-md-first',
    0: 'order-md-0',
    1: 'order-md-1',
    2: 'order-md-2',
    3: 'order-md-3',
    4: 'order-md-4',
    5: 'order-md-5',
    last: 'order-md-last',
  },
  'order-lg': {
    first: 'order-lg-first',
    0: 'order-lg-0',
    1: 'order-lg-1',
    2: 'order-lg-2',
    3: 'order-lg-3',
    4: 'order-lg-4',
    5: 'order-lg-5',
    last: 'order-lg-last',
  },
  'order-xl': {
    first: 'order-xl-first',
    0: 'order-xl-0',
    1: 'order-xl-1',
    2: 'order-xl-2',
    3: 'order-xl-3',
    4: 'order-xl-4',
    5: 'order-xl-5',
    last: 'order-xl-last',
  },
  'order-xxl': {
    first: 'order-xxl-first',
    0: 'order-xxl-0',
    1: 'order-xxl-1',
    2: 'order-xxl-2',
    3: 'order-xxl-3',
    4: 'order-xxl-4',
    5: 'order-xxl-5',
    last: 'order-xxl-last',
  },
};

export default FLEX;
