const SPACING = {
  margin: {
    0: 'm-0',
    1: 'm-1',
    2: 'm-2',
    3: 'm-3',
    4: 'm-4',
    5: 'm-5',
    auto: 'm-auto',
  },
  'margin-sm': {
    0: 'm-sm-0',
    1: 'm-sm-1',
    2: 'm-sm-2',
    3: 'm-sm-3',
    4: 'm-sm-4',
    5: 'm-sm-5',
    auto: 'm-sm-auto',
  },
  'margin-md': {
    0: 'm-md-0',
    1: 'm-md-1',
    2: 'm-md-2',
    3: 'm-md-3',
    4: 'm-md-4',
    5: 'm-md-5',
    auto: 'm-md-auto',
  },
  'margin-lg': {
    0: 'm-lg-0',
    1: 'm-lg-1',
    2: 'm-lg-2',
    3: 'm-lg-3',
    4: 'm-lg-4',
    5: 'm-lg-5',
    auto: 'm-lg-auto',
  },
  'margin-xl': {
    0: 'm-xl-0',
    1: 'm-xl-1',
    2: 'm-xl-2',
    3: 'm-xl-3',
    4: 'm-xl-4',
    5: 'm-xl-5',
    auto: 'm-xl-auto',
  },
  'margin-xxl': {
    0: 'm-xxl-0',
    1: 'm-xxl-1',
    2: 'm-xxl-2',
    3: 'm-xxl-3',
    4: 'm-xxl-4',
    5: 'm-xxl-5',
    auto: 'm-xxl-auto',
  },
  'margin-top': {
    0: 'mt-0',
    1: 'mt-1',
    2: 'mt-2',
    3: 'mt-3',
    4: 'mt-4',
    5: 'mt-5',
    auto: 'mt-auto',
  },
  'margin-top-sm': {
    0: 'mt-sm-0',
    1: 'mt-sm-1',
    2: 'mt-sm-2',
    3: 'mt-sm-3',
    4: 'mt-sm-4',
    5: 'mt-sm-5',
    auto: 'mt-sm-auto',
  },
  'margin-top-md': {
    0: 'mt-md-0',
    1: 'mt-md-1',
    2: 'mt-md-2',
    3: 'mt-md-3',
    4: 'mt-md-4',
    5: 'mt-md-5',
    auto: 'mt-md-auto',
  },
  'margin-top-lg': {
    0: 'mt-lg-0',
    1: 'mt-lg-1',
    2: 'mt-lg-2',
    3: 'mt-lg-3',
    4: 'mt-lg-4',
    5: 'mt-lg-5',
    auto: 'mt-lg-auto',
  },
  'margin-top-xl': {
    0: 'mt-xl-0',
    1: 'mt-xl-1',
    2: 'mt-xl-2',
    3: 'mt-xl-3',
    4: 'mt-xl-4',
    5: 'mt-xl-5',
    auto: 'mt-xl-auto',
  },
  'margin-top-xxl': {
    0: 'mt-xxl-0',
    1: 'mt-xxl-1',
    2: 'mt-xxl-2',
    3: 'mt-xxl-3',
    4: 'mt-xxl-4',
    5: 'mt-xxl-5',
    auto: 'mt-xxl-auto',
  },
  'margin-bottom': {
    0: 'mb-0',
    1: 'mb-1',
    2: 'mb-2',
    3: 'mb-3',
    4: 'mb-4',
    5: 'mb-5',
    auto: 'mb-auto',
  },
  'margin-bottom-sm': {
    0: 'mb-sm-0',
    1: 'mb-sm-1',
    2: 'mb-sm-2',
    3: 'mb-sm-3',
    4: 'mb-sm-4',
    5: 'mb-sm-5',
    auto: 'mb-sm-auto',
  },
  'margin-bottom-md': {
    0: 'mb-md-0',
    1: 'mb-md-1',
    2: 'mb-md-2',
    3: 'mb-md-3',
    4: 'mb-md-4',
    5: 'mb-md-5',
    auto: 'mb-md-auto',
  },
  'margin-bottom-lg': {
    0: 'mb-lg-0',
    1: 'mb-lg-1',
    2: 'mb-lg-2',
    3: 'mb-lg-3',
    4: 'mb-lg-4',
    5: 'mb-lg-5',
    auto: 'mb-lg-auto',
  },
  'margin-bottom-xl': {
    0: 'mb-xl-0',
    1: 'mb-xl-1',
    2: 'mb-xl-2',
    3: 'mb-xl-3',
    4: 'mb-xl-4',
    5: 'mb-xl-5',
    auto: 'mb-xl-auto',
  },
  'margin-bottom-xxl': {
    0: 'mb-xxl-0',
    1: 'mb-xxl-1',
    2: 'mb-xxl-2',
    3: 'mb-xxl-3',
    4: 'mb-xxl-4',
    5: 'mb-xxl-5',
    auto: 'mb-xxl-auto',
  },
  'margin-start': {
    0: 'ms-0',
    1: 'ms-1',
    2: 'ms-2',
    3: 'ms-3',
    4: 'ms-4',
    5: 'ms-5',
    auto: 'ms-auto',
  },
  'margin-start-sm': {
    0: 'ms-sm-0',
    1: 'ms-sm-1',
    2: 'ms-sm-2',
    3: 'ms-sm-3',
    4: 'ms-sm-4',
    5: 'ms-sm-5',
    auto: 'ms-sm-auto',
  },
  'margin-start-md': {
    0: 'ms-md-0',
    1: 'ms-md-1',
    2: 'ms-md-2',
    3: 'ms-md-3',
    4: 'ms-md-4',
    5: 'ms-md-5',
    auto: 'ms-md-auto',
  },
  'margin-start-lg': {
    0: 'ms-lg-0',
    1: 'ms-lg-1',
    2: 'ms-lg-2',
    3: 'ms-lg-3',
    4: 'ms-lg-4',
    5: 'ms-lg-5',
    auto: 'ms-lg-auto',
  },
  'margin-start-xl': {
    0: 'ms-xl-0',
    1: 'ms-xl-1',
    2: 'ms-xl-2',
    3: 'ms-xl-3',
    4: 'ms-xl-4',
    5: 'ms-xl-5',
    auto: 'ms-xl-auto',
  },
  'margin-start-xxl': {
    0: 'ms-xxl-0',
    1: 'ms-xxl-1',
    2: 'ms-xxl-2',
    3: 'ms-xxl-3',
    4: 'ms-xxl-4',
    5: 'ms-xxl-5',
    auto: 'ms-xxl-auto',
  },
  'margin-end': {
    0: 'me-0',
    1: 'me-1',
    2: 'me-2',
    3: 'me-3',
    4: 'me-4',
    5: 'me-5',
    auto: 'me-auto',
  },
  'margin-end-sm': {
    0: 'me-sm-0',
    1: 'me-sm-1',
    2: 'me-sm-2',
    3: 'me-sm-3',
    4: 'me-sm-4',
    5: 'me-sm-5',
    auto: 'me-sm-auto',
  },
  'margin-end-md': {
    0: 'me-md-0',
    1: 'me-md-1',
    2: 'me-md-2',
    3: 'me-md-3',
    4: 'me-md-4',
    5: 'me-md-5',
    auto: 'me-md-auto',
  },
  'margin-end-lg': {
    0: 'me-lg-0',
    1: 'me-lg-1',
    2: 'me-lg-2',
    3: 'me-lg-3',
    4: 'me-lg-4',
    5: 'me-lg-5',
    auto: 'me-lg-auto',
  },
  'margin-end-xl': {
    0: 'me-xl-0',
    1: 'me-xl-1',
    2: 'me-xl-2',
    3: 'me-xl-3',
    4: 'me-xl-4',
    5: 'me-xl-5',
    auto: 'me-xl-auto',
  },
  'margin-end-xxl': {
    0: 'me-xxl-0',
    1: 'me-xxl-1',
    2: 'me-xxl-2',
    3: 'me-xxl-3',
    4: 'me-xxl-4',
    5: 'me-xxl-5',
    auto: 'me-xxl-auto',
  },
  'margin-y': {
    0: 'my-0',
    1: 'my-1',
    2: 'my-2',
    3: 'my-3',
    4: 'my-4',
    5: 'my-5',
    auto: 'my-auto',
  },
  'margin-y-sm': {
    0: 'my-sm-0',
    1: 'my-sm-1',
    2: 'my-sm-2',
    3: 'my-sm-3',
    4: 'my-sm-4',
    5: 'my-sm-5',
    auto: 'my-sm-auto',
  },
  'margin-y-md': {
    0: 'my-md-0',
    1: 'my-md-1',
    2: 'my-md-2',
    3: 'my-md-3',
    4: 'my-md-4',
    5: 'my-md-5',
    auto: 'my-md-auto',
  },
  'margin-y-lg': {
    0: 'my-lg-0',
    1: 'my-lg-1',
    2: 'my-lg-2',
    3: 'my-lg-3',
    4: 'my-lg-4',
    5: 'my-lg-5',
    auto: 'my-lg-auto',
  },
  'margin-y-xl': {
    0: 'my-xl-0',
    1: 'my-xl-1',
    2: 'my-xl-2',
    3: 'my-xl-3',
    4: 'my-xl-4',
    5: 'my-xl-5',
    auto: 'my-xl-auto',
  },
  'margin-y-xxl': {
    0: 'my-xxl-0',
    1: 'my-xxl-1',
    2: 'my-xxl-2',
    3: 'my-xxl-3',
    4: 'my-xxl-4',
    5: 'my-xxl-5',
    auto: 'my-xxl-auto',
  },
  'margin-x': {
    0: 'mx-0',
    1: 'mx-1',
    2: 'mx-2',
    3: 'mx-3',
    4: 'mx-4',
    5: 'mx-5',
    auto: 'mx-auto',
  },
  'margin-x-sm': {
    0: 'mx-sm-0',
    1: 'mx-sm-1',
    2: 'mx-sm-2',
    3: 'mx-sm-3',
    4: 'mx-sm-4',
    5: 'mx-sm-5',
    auto: 'mx-sm-auto',
  },
  'margin-x-md': {
    0: 'mx-md-0',
    1: 'mx-md-1',
    2: 'mx-md-2',
    3: 'mx-md-3',
    4: 'mx-md-4',
    5: 'mx-md-5',
    auto: 'mx-md-auto',
  },
  'margin-x-lg': {
    0: 'mx-lg-0',
    1: 'mx-lg-1',
    2: 'mx-lg-2',
    3: 'mx-lg-3',
    4: 'mx-lg-4',
    5: 'mx-lg-5',
    auto: 'mx-lg-auto',
  },
  'margin-x-xl': {
    0: 'mx-xl-0',
    1: 'mx-xl-1',
    2: 'mx-xl-2',
    3: 'mx-xl-3',
    4: 'mx-xl-4',
    5: 'mx-xl-5',
    auto: 'mx-xl-auto',
  },
  'margin-x-xxl': {
    0: 'mx-xxl-0',
    1: 'mx-xxl-1',
    2: 'mx-xxl-2',
    3: 'mx-xxl-3',
    4: 'mx-xxl-4',
    5: 'mx-xxl-5',
    auto: 'mx-xxl-auto',
  },
  padding: {
    0: 'p-0',
    1: 'p-1',
    2: 'p-2',
    3: 'p-3',
    4: 'p-4',
    5: 'p-5',
    auto: 'p-auto',
  },
  'padding-sm': {
    0: 'p-sp-0',
    1: 'p-sp-1',
    2: 'p-sp-2',
    3: 'p-sp-3',
    4: 'p-sp-4',
    5: 'p-sp-5',
    auto: 'p-sp-auto',
  },
  'padding-md': {
    0: 'p-md-0',
    1: 'p-md-1',
    2: 'p-md-2',
    3: 'p-md-3',
    4: 'p-md-4',
    5: 'p-md-5',
    auto: 'p-md-auto',
  },
  'padding-lg': {
    0: 'p-lg-0',
    1: 'p-lg-1',
    2: 'p-lg-2',
    3: 'p-lg-3',
    4: 'p-lg-4',
    5: 'p-lg-5',
    auto: 'p-lg-auto',
  },
  'padding-xl': {
    0: 'p-xl-0',
    1: 'p-xl-1',
    2: 'p-xl-2',
    3: 'p-xl-3',
    4: 'p-xl-4',
    5: 'p-xl-5',
    auto: 'p-xl-auto',
  },
  'padding-xxl': {
    0: 'p-xxl-0',
    1: 'p-xxl-1',
    2: 'p-xxl-2',
    3: 'p-xxl-3',
    4: 'p-xxl-4',
    5: 'p-xxl-5',
    auto: 'p-xxl-auto',
  },
  'padding-top': {
    0: 'pt-0',
    1: 'pt-1',
    2: 'pt-2',
    3: 'pt-3',
    4: 'pt-4',
    5: 'pt-5',
    auto: 'pt-auto',
  },
  'padding-top-sm': {
    0: 'pt-sp-0',
    1: 'pt-sp-1',
    2: 'pt-sp-2',
    3: 'pt-sp-3',
    4: 'pt-sp-4',
    5: 'pt-sp-5',
    auto: 'pt-sp-auto',
  },
  'padding-top-md': {
    0: 'pt-md-0',
    1: 'pt-md-1',
    2: 'pt-md-2',
    3: 'pt-md-3',
    4: 'pt-md-4',
    5: 'pt-md-5',
    auto: 'pt-md-auto',
  },
  'padding-top-lg': {
    0: 'pt-lg-0',
    1: 'pt-lg-1',
    2: 'pt-lg-2',
    3: 'pt-lg-3',
    4: 'pt-lg-4',
    5: 'pt-lg-5',
    auto: 'pt-lg-auto',
  },
  'padding-top-xl': {
    0: 'pt-xl-0',
    1: 'pt-xl-1',
    2: 'pt-xl-2',
    3: 'pt-xl-3',
    4: 'pt-xl-4',
    5: 'pt-xl-5',
    auto: 'pt-xl-auto',
  },
  'padding-top-xxl': {
    0: 'pt-xxl-0',
    1: 'pt-xxl-1',
    2: 'pt-xxl-2',
    3: 'pt-xxl-3',
    4: 'pt-xxl-4',
    5: 'pt-xxl-5',
    auto: 'pt-xxl-auto',
  },
  'padding-bottom': {
    0: 'pb-0',
    1: 'pb-1',
    2: 'pb-2',
    3: 'pb-3',
    4: 'pb-4',
    5: 'pb-5',
    auto: 'pb-auto',
  },
  'padding-bottom-sm': {
    0: 'pb-sp-0',
    1: 'pb-sp-1',
    2: 'pb-sp-2',
    3: 'pb-sp-3',
    4: 'pb-sp-4',
    5: 'pb-sp-5',
    auto: 'pb-sp-auto',
  },
  'padding-bottom-md': {
    0: 'pb-md-0',
    1: 'pb-md-1',
    2: 'pb-md-2',
    3: 'pb-md-3',
    4: 'pb-md-4',
    5: 'pb-md-5',
    auto: 'pb-md-auto',
  },
  'padding-bottom-lg': {
    0: 'pb-lg-0',
    1: 'pb-lg-1',
    2: 'pb-lg-2',
    3: 'pb-lg-3',
    4: 'pb-lg-4',
    5: 'pb-lg-5',
    auto: 'pb-lg-auto',
  },
  'padding-bottom-xl': {
    0: 'pb-xl-0',
    1: 'pb-xl-1',
    2: 'pb-xl-2',
    3: 'pb-xl-3',
    4: 'pb-xl-4',
    5: 'pb-xl-5',
    auto: 'pb-xl-auto',
  },
  'padding-bottom-xxl': {
    0: 'pb-xxl-0',
    1: 'pb-xxl-1',
    2: 'pb-xxl-2',
    3: 'pb-xxl-3',
    4: 'pb-xxl-4',
    5: 'pb-xxl-5',
    auto: 'pb-xxl-auto',
  },
  'padding-start': {
    0: 'ps-0',
    1: 'ps-1',
    2: 'ps-2',
    3: 'ps-3',
    4: 'ps-4',
    5: 'ps-5',
    auto: 'ps-auto',
  },
  'padding-start-sm': {
    0: 'ps-sp-0',
    1: 'ps-sp-1',
    2: 'ps-sp-2',
    3: 'ps-sp-3',
    4: 'ps-sp-4',
    5: 'ps-sp-5',
    auto: 'ps-sp-auto',
  },
  'padding-start-md': {
    0: 'ps-md-0',
    1: 'ps-md-1',
    2: 'ps-md-2',
    3: 'ps-md-3',
    4: 'ps-md-4',
    5: 'ps-md-5',
    auto: 'ps-md-auto',
  },
  'padding-start-lg': {
    0: 'ps-lg-0',
    1: 'ps-lg-1',
    2: 'ps-lg-2',
    3: 'ps-lg-3',
    4: 'ps-lg-4',
    5: 'ps-lg-5',
    auto: 'ps-lg-auto',
  },
  'padding-start-xl': {
    0: 'ps-xl-0',
    1: 'ps-xl-1',
    2: 'ps-xl-2',
    3: 'ps-xl-3',
    4: 'ps-xl-4',
    5: 'ps-xl-5',
    auto: 'ps-xl-auto',
  },
  'padding-start-xxl': {
    0: 'ps-xxl-0',
    1: 'ps-xxl-1',
    2: 'ps-xxl-2',
    3: 'ps-xxl-3',
    4: 'ps-xxl-4',
    5: 'ps-xxl-5',
    auto: 'ps-xxl-auto',
  },
  'padding-end': {
    0: 'pe-0',
    1: 'pe-1',
    2: 'pe-2',
    3: 'pe-3',
    4: 'pe-4',
    5: 'pe-5',
    auto: 'pe-auto',
  },
  'padding-end-sm': {
    0: 'pe-sp-0',
    1: 'pe-sp-1',
    2: 'pe-sp-2',
    3: 'pe-sp-3',
    4: 'pe-sp-4',
    5: 'pe-sp-5',
    auto: 'pe-sp-auto',
  },
  'padding-end-md': {
    0: 'pe-md-0',
    1: 'pe-md-1',
    2: 'pe-md-2',
    3: 'pe-md-3',
    4: 'pe-md-4',
    5: 'pe-md-5',
    auto: 'pe-md-auto',
  },
  'padding-end-lg': {
    0: 'pe-lg-0',
    1: 'pe-lg-1',
    2: 'pe-lg-2',
    3: 'pe-lg-3',
    4: 'pe-lg-4',
    5: 'pe-lg-5',
    auto: 'pe-lg-auto',
  },
  'padding-end-xl': {
    0: 'pe-xl-0',
    1: 'pe-xl-1',
    2: 'pe-xl-2',
    3: 'pe-xl-3',
    4: 'pe-xl-4',
    5: 'pe-xl-5',
    auto: 'pe-xl-auto',
  },
  'padding-end-xxl': {
    0: 'pe-xxl-0',
    1: 'pe-xxl-1',
    2: 'pe-xxl-2',
    3: 'pe-xxl-3',
    4: 'pe-xxl-4',
    5: 'pe-xxl-5',
    auto: 'pe-xxl-auto',
  },
  'padding-y': {
    0: 'py-0',
    1: 'py-1',
    2: 'py-2',
    3: 'py-3',
    4: 'py-4',
    5: 'py-5',
    auto: 'py-auto',
  },
  'padding-y-sm': {
    0: 'py-sp-0',
    1: 'py-sp-1',
    2: 'py-sp-2',
    3: 'py-sp-3',
    4: 'py-sp-4',
    5: 'py-sp-5',
    auto: 'py-sp-auto',
  },
  'padding-y-md': {
    0: 'py-md-0',
    1: 'py-md-1',
    2: 'py-md-2',
    3: 'py-md-3',
    4: 'py-md-4',
    5: 'py-md-5',
    auto: 'py-md-auto',
  },
  'padding-y-lg': {
    0: 'py-lg-0',
    1: 'py-lg-1',
    2: 'py-lg-2',
    3: 'py-lg-3',
    4: 'py-lg-4',
    5: 'py-lg-5',
    auto: 'py-lg-auto',
  },
  'padding-y-xl': {
    0: 'py-xl-0',
    1: 'py-xl-1',
    2: 'py-xl-2',
    3: 'py-xl-3',
    4: 'py-xl-4',
    5: 'py-xl-5',
    auto: 'py-xl-auto',
  },
  'padding-y-xxl': {
    0: 'py-xxl-0',
    1: 'py-xxl-1',
    2: 'py-xxl-2',
    3: 'py-xxl-3',
    4: 'py-xxl-4',
    5: 'py-xxl-5',
    auto: 'py-xxl-auto',
  },
  'padding-x': {
    0: 'px-0',
    1: 'px-1',
    2: 'px-2',
    3: 'px-3',
    4: 'px-4',
    5: 'px-5',
    auto: 'px-auto',
  },
  'padding-x-sm': {
    0: 'px-sp-0',
    1: 'px-sp-1',
    2: 'px-sp-2',
    3: 'px-sp-3',
    4: 'px-sp-4',
    5: 'px-sp-5',
    auto: 'px-sp-auto',
  },
  'padding-x-md': {
    0: 'px-md-0',
    1: 'px-md-1',
    2: 'px-md-2',
    3: 'px-md-3',
    4: 'px-md-4',
    5: 'px-md-5',
    auto: 'px-md-auto',
  },
  'padding-x-lg': {
    0: 'px-lg-0',
    1: 'px-lg-1',
    2: 'px-lg-2',
    3: 'px-lg-3',
    4: 'px-lg-4',
    5: 'px-lg-5',
    auto: 'px-lg-auto',
  },
  'padding-x-xl': {
    0: 'px-xl-0',
    1: 'px-xl-1',
    2: 'px-xl-2',
    3: 'px-xl-3',
    4: 'px-xl-4',
    5: 'px-xl-5',
    auto: 'px-xl-auto',
  },
  'padding-x-xxl': {
    0: 'px-xxl-0',
    1: 'px-xxl-1',
    2: 'px-xxl-2',
    3: 'px-xxl-3',
    4: 'px-xxl-4',
    5: 'px-xxl-5',
    auto: 'px-xxl-auto',
  },
};

export default SPACING;
