const MarginDefaultProps = {
  margin: false,
  marginTop: false,
  marginVertical: false,
  marginBottom: false,
  marginRight: false,
  marginHorizontal: false,
  marginLeft: false,
  marginTopXs: false,
  marginVerticalXs: false,
  marginBottomXs: false,
  marginRightXs: false,
  marginHorizontalXs: false,
  marginLeftXs: false,
  marginTopSm: false,
  marginVerticalSm: false,
  marginBottomSm: false,
  marginRightSm: false,
  marginHorizontalSm: false,
  marginLeftSm: false,
  marginTopMd: false,
  marginVerticalMd: false,
  marginBottomMd: false,
  marginRightMd: false,
  marginHorizontalMd: false,
  marginLeftMd: false,
  marginTopLg: false,
  marginVerticalLg: false,
  marginBottomLg: false,
  marginRightLg: false,
  marginHorizontalLg: false,
  marginLeftLg: false,
  marginTopXl: false,
  marginVerticalXl: false,
  marginBottomXl: false,
  marginRightXl: false,
  marginHorizontalXl: false,
  marginLeftXl: false,
};

export default MarginDefaultProps;
