const SpacingDefaultProps = {
  margin: false,
  marginTop: false,
  marginVertical: false,
  marginBottom: false,
  marginRight: false,
  marginHorizontal: false,
  marginLeft: false,

  marginSm: false,
  marginTopSm: false,
  marginVerticalSm: false,
  marginBottomSm: false,
  marginRightSm: false,
  marginHorizontalSm: false,
  marginLeftSm: false,

  marginMd: false,
  marginTopMd: false,
  marginVerticalMd: false,
  marginBottomMd: false,
  marginRightMd: false,
  marginHorizontalMd: false,
  marginLeftMd: false,

  marginLg: false,
  marginTopLg: false,
  marginVerticalLg: false,
  marginBottomLg: false,
  marginRightLg: false,
  marginHorizontalLg: false,
  marginLeftLg: false,

  marginXl: false,
  marginTopXl: false,
  marginVerticalXl: false,
  marginBottomXl: false,
  marginRightXl: false,
  marginHorizontalXl: false,
  marginLeftXl: false,

  padding: false,
  paddingTop: false,
  paddingVertical: false,
  paddingBottom: false,
  paddingRight: false,
  paddingHorizontal: false,
  paddingLeft: false,

  paddingSm: false,
  paddingTopSm: false,
  paddingVerticalSm: false,
  paddingBottomSm: false,
  paddingRightSm: false,
  paddingHorizontalSm: false,
  paddingLeftSm: false,

  paddingMd: false,
  paddingTopMd: false,
  paddingVerticalMd: false,
  paddingBottomMd: false,
  paddingRightMd: false,
  paddingHorizontalMd: false,
  paddingLeftMd: false,

  paddingLg: false,
  paddingTopLg: false,
  paddingVerticalLg: false,
  paddingBottomLg: false,
  paddingRightLg: false,
  paddingHorizontalLg: false,
  paddingLeftLg: false,

  paddingXl: false,
  paddingTopXl: false,
  paddingVerticalXl: false,
  paddingBottomXl: false,
  paddingRightXl: false,
  paddingHorizontalXl: false,
  paddingLeftXl: false,
};

export default SpacingDefaultProps;
