const PaddingDefaultProps = {
  padding: false,
  paddingTop: false,
  paddingVertical: false,
  paddingBottom: false,
  paddingRight: false,
  paddingHorizontal: false,
  paddingLeft: false,
  paddingTopXs: false,
  paddingVerticalXs: false,
  paddingBottomXs: false,
  paddingRightXs: false,
  paddingHorizontalXs: false,
  paddingLeftXs: false,
  paddingTopSm: false,
  paddingVerticalSm: false,
  paddingBottomSm: false,
  paddingRightSm: false,
  paddingHorizontalSm: false,
  paddingLeftSm: false,
  paddingTopMd: false,
  paddingVerticalMd: false,
  paddingBottomMd: false,
  paddingRightMd: false,
  paddingHorizontalMd: false,
  paddingLeftMd: false,
  paddingTopLg: false,
  paddingVerticalLg: false,
  paddingBottomLg: false,
  paddingRightLg: false,
  paddingHorizontalLg: false,
  paddingLeftLg: false,
  paddingTopXl: false,
  paddingVerticalXl: false,
  paddingBottomXl: false,
  paddingRightXl: false,
  paddingHorizontalXl: false,
  paddingLeftXl: false,
};

export default PaddingDefaultProps;
